apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 4
  selector:
    matchLabels:
      app: converter
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: converter
    spec: 
      containers:
        - name: converter
          image: vivek1508/consumer:1.0
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: ls
                

